plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
#remote_theme: chrisrhymes/bulma-clean-theme
#remote_theme: aterenin/minima-reboot
theme: minima
title: dmatik
description: Smart Home Tutorials
readme_index:
  with_frontmatter: false
header_pages:
